import '../styles/globals.css';
import { ChakraProvider } from "@chakra-ui/react";
import { Flex } from "@chakra-ui/react";
import { Container } from "@chakra-ui/react";
import Head from 'next/head';
import Header from '../components/header';

function MyApp({ Component, pageProps }) {
  return (
    <ChakraProvider>
      <Flex flexDirection="column" minHeight="max">
      <Header />
      <Container maxW="container.xl">
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Component {...pageProps} />
      </Container>
        <footer>
          footer stuff
        </footer>
      </Flex>
    </ChakraProvider>
  );
}

export default MyApp;
