import Head from 'next/head';

const Films = () => {
  return (
    <>
      <Head>
        <title>Films</title>
        <meta name="films" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        films
      </main>
    </>  
  );
};

export default Films;
