import { VStack } from '@chakra-ui/react';
import Head from 'next/head';
import FilmItem from '../components/films/FilmItem';

const Films = () => {
  return (
    <>
      <Head>
        <title>Films</title>
        <meta name="films" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <VStack>
        <FilmItem />
      </VStack>
    </>  
  );
};

export default Films;
