import Head from 'next/head';

const News = () => {
  return (
    <>
      <Head>
        <title>News</title>
        <meta name="news" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        news
      </main>
    </>
  );
};

export default News;
