import { Flex } from "@chakra-ui/react";
import { Container } from "@chakra-ui/react";
import Head from 'next/head';
import Header from '../components/header';

export default function Home() {
  return (
    <Flex flexDirection="column" minHeight="max">
      <Header />
      <Container maxW="container.xl">
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main>
          main stuff
        </main>
        <footer>
        footer stuff
        </footer>
      </Container>
    </Flex>
  );
}
