import Head from 'next/head';

const People = () => {
  return (
    <>
      <Head>
        <title>People</title>
        <meta name="people" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        people
      </main>
    </>
  );
};

export default People;
