import Head from 'next/head';

const Planets = () => {
  return (
    <>
      <Head>
        <title>Planets</title>
        <meta name="planets" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        planets
       </main>
    </>
  );
};

export default Planets;
