import { Flex } from "@chakra-ui/react";
import { Container } from "@chakra-ui/react";
import Head from 'next/head';
import Header from '../components/header';

const Species = () => {
  return (
    <Flex flexDirection="column" minHeight="max">
      <Header />
      <Container maxW="container.xl">
        <Head>
          <title>Species</title>
          <meta name="species" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main>
          species
        </main>
        <footer>
          footer stuff
        </footer>
      </Container>
    </Flex>
  );
};

export default Species;
