import Head from 'next/head';

const Species = () => {
  return (
    <>
      <Head>
        <title>Species</title>
        <meta name="species" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        species
      </main>
    </>
  );
};

export default Species;
