import Head from 'next/head';

const Starships = () => {
  return (
    <>
      <Head>
        <title>Starships</title>
        <meta name="starships" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        starships
      </main>
    </>
  );
};

export default Starships;
