import Head from 'next/head';

const Vehicles = () => {
  return (
    <>
      <Head>
        <title>Vehicles</title>
        <meta name="vehicles" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        vehicles
      </main>
    </>
  );
};

export default Vehicles;
